name: Ubuntu 18.04

on: [ push, pull_request ]

env:
  APT_INSTALL: sudo apt-get install -yq --no-install-suggests --no-install-recommends --allow-unauthenticated --allow-downgrades --allow-change-held-packages

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [ g++-6, g++-5 ]
        std: [ 11, 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create Build Environment
        run: |
          mkdir ${{ runner.workspace }}/install
          cd ${{ runner.workspace }}/install
          
          sudo locale-gen en_US.UTF-8
          sudo locale-gen fi_FI.UTF-8
          sudo update-locale
          sudo locale -a
          
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get --allow-unauthenticated -yq update
          
          ${APT_INSTALL} ${{ matrix.cxx }}

      - name: Build
        env:
          CXX: ${{ matrix.cxx }}
          STD: ${{ matrix.std }}
        shell: bash
        run: |
          mkdir ${{ runner.workspace }}/build
          cd ${{ runner.workspace }}/build
          
          cmake -DSCN_BUILD_LOCALIZED_TESTS=ON -DSCN_WERROR=ON -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_CXX_STANDARD=$STD \
                $GITHUB_WORKSPACE
          make -k -j2
          ctest --output-on-failure
